name: Build Spring Test

on:
  push:
    paths:
      - '.github/**'
      - 'apps/spring-test/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: japudcret/speelplaats/spring-test

jobs:
  build-spring-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: ./apps/spring-test/
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
    - name: Setup Gradle
      uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
      with:
        gradle-version: 8.4
    - name: Execute Gradle build
      run: ./gradlew jib
      env:
        IMAGE_NAME: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}